apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-gclv
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0056-tenant/tkrw-pr712-0075-0056-app/devfile-sample-gclv@sha256:89c9689b119bdf84399a7eda70645934e2352badd8aa6d54f4a9cab521fc5e81
        name: my-nodejs
        resources: {}
status: {}
